export default {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",

  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",

  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",

  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",

  PRODUCT_INCREMENT: "PRODUCT_INCREMENT",
  PRODUCT_DECREMENT: "PRODUCT_DECREMENT",

  VNPAY_PAYMENT: "VNPAY_PAYMENT",
  VNPAY_PAYMENT_SUCCESS: "VNPAY_PAYMENT_SUCCESS",
  VNPAY_PAYMENT_FAILED: "VNPAY_PAYMENT_FAILED",

  CHECKOUT: "CHECKOUT",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILED: "CHECKOUT_FAILED",
};
