export default {
  GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",

  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",

  PRODUCT_INCREMENT: "PRODUCT_INCREMENT",
  PRODUCT_DECREMENT: "PRODUCT_DECREMENT",

  VNPAY_PAYMENT: "VNPAY_PAYMENT",
  VNPAY_PAYMENT_SUCCESS: "VNPAY_PAYMENT_SUCCESS",
  VNPAY_PAYMENT_FAILED: "VNPAY_PAYMENT_FAILED",
};
